Repository unopim/unopim, pull requests merged in 2024-10, with the labels that each got.

#32 Feature/account page improvement
  packages/Webkul/Admin/src/Http/Controllers/User/AccountController.php
  packages/Webkul/Admin/src/Resources/lang/ar_AE/app.php
  packages/Webkul/Admin/src/Resources/lang/de_DE/app.php
  packages/Webkul/Admin/src/Resources/lang/en_US/app.php
  packages/Webkul/Admin/src/Resources/lang/es_ES/app.php
  packages/Webkul/Admin/src/Resources/lang/fr_FR/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/id_ID/app.php
  packages/Webkul/Admin/src/Resources/lang/ja_JP/app.php
  packages/Webkul/Admin/src/Resources/lang/mn_MN/app.php
  packages/Webkul/Admin/src/Resources/lang/nl_NL/app.php
  packages/Webkul/Admin/src/Resources/lang/ru_RU/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/account/edit.blade.php
  packages/Webkul/User/tests/Feature/UserTest.php
Labels: under review

#36 Feature/terminal job
  packages/Webkul/Admin/src/Http/Controllers/Settings/DataTransfer/ExportController.php
  packages/Webkul/Admin/tests/Feature/DataTransfer/Command/JobLauncherTest.php
  packages/Webkul/Admin/tests/Feature/DataTransfer/ExportTest.php
  packages/Webkul/DataTransfer/src/Console/JobExecuteCommand.php
  packages/Webkul/DataTransfer/src/Helpers/Export.php
  packages/Webkul/DataTransfer/src/Helpers/Exporters/AbstractExporter.php
  packages/Webkul/DataTransfer/src/Helpers/Import.php
  packages/Webkul/DataTransfer/src/Helpers/Importers/AbstractImporter.php
  packages/Webkul/DataTransfer/src/Jobs/Export/ExportTrackBatch.php
  packages/Webkul/DataTransfer/src/Jobs/Import/ImportTrackBatch.php
  packages/Webkul/DataTransfer/src/Providers/DataTransferServiceProvider.php
  packages/Webkul/DataTransfer/src/Queue/Worker.php
Labels: under review, QA Tested

#30 feat: export filters component improvement and job-logger
  packages/Webkul/Admin/src/Http/Controllers/Catalog/Options/AjaxOptionsController.php
  packages/Webkul/Admin/src/Http/Controllers/Settings/DataTransfer/ExportController.php
  packages/Webkul/Admin/src/Http/Controllers/Settings/DataTransfer/TrackerController.php
  packages/Webkul/Admin/src/Resources/lang/ar_AE/app.php
  packages/Webkul/Admin/src/Resources/lang/de_DE/app.php
  packages/Webkul/Admin/src/Resources/lang/en_US/app.php
  packages/Webkul/Admin/src/Resources/lang/es_ES/app.php
  packages/Webkul/Admin/src/Resources/lang/fr_FR/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/id_ID/app.php
  packages/Webkul/Admin/src/Resources/lang/ja_JP/app.php
  packages/Webkul/Admin/src/Resources/lang/mn_MN/app.php
  packages/Webkul/Admin/src/Resources/lang/nl_NL/app.php
  packages/Webkul/Admin/src/Resources/lang/ru_RU/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/components/data-transfer/filter-fields.blade.php
  packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/data-transfer/exports/create.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/data-transfer/exports/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/data-transfer/exports/export.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/data-transfer/tracker/import.blade.php
  packages/Webkul/Admin/src/Routes/settings-routes.php
  packages/Webkul/DataTransfer/src/Config/exporters.php
  packages/Webkul/DataTransfer/src/Contracts/Validator/JobInstances/JobValidator.php
  packages/Webkul/DataTransfer/src/Helpers/Export.php
  packages/Webkul/DataTransfer/src/Helpers/Exporters/AbstractExporter.php
  packages/Webkul/DataTransfer/src/Helpers/Exporters/Category/Exporter.php
  packages/Webkul/DataTransfer/src/Helpers/Import.php
  packages/Webkul/DataTransfer/src/Helpers/Importers/AbstractImporter.php
  packages/Webkul/DataTransfer/src/Jobs/Export/Completed.php
  packages/Webkul/DataTransfer/src/Jobs/Export/ExportBatch.php
  packages/Webkul/DataTransfer/src/Jobs/Export/ExportTrackBatch.php
  packages/Webkul/DataTransfer/src/Jobs/Import/Completed.php
  packages/Webkul/DataTransfer/src/Jobs/Import/ImportBatch.php
  packages/Webkul/DataTransfer/src/Jobs/Import/ImportTrackBatch.php
  packages/Webkul/DataTransfer/src/Resources/lang/ar_AE/app.php
  packages/Webkul/DataTransfer/src/Resources/lang/de_DE/app.php
  packages/Webkul/DataTransfer/src/Resources/lang/en_US/app.php
  packages/Webkul/DataTransfer/src/Resources/lang/es_ES/app.php
  packages/Webkul/DataTransfer/src/Resources/lang/fr_FR/app.php
  packages/Webkul/DataTransfer/src/Resources/lang/hi_IN/app.php
  packages/Webkul/DataTransfer/src/Resources/lang/id_ID/app.php
  packages/Webkul/DataTransfer/src/Resources/lang/mn_MN/app.php
  packages/Webkul/DataTransfer/src/Resources/lang/nl_NL/app.php
  packages/Webkul/DataTransfer/src/Resources/lang/ru_RU/app.php
  packages/Webkul/DataTransfer/src/Resources/lang/zh_CN/app.php
  packages/Webkul/DataTransfer/src/Services/JobLogger.php
  packages/Webkul/DataTransfer/src/Validators/JobInstances/Default/JobValidator.php
  packages/Webkul/DataTransfer/src/Validators/JobInstances/Export/CategoryJobValidator.php
  packages/Webkul/DataTransfer/src/Validators/JobInstances/Export/ProductJobValidator.php
  public/themes/admin/default/build/assets/app-6adebe11.css
  public/themes/admin/default/build/assets/app-9cce44f5.css
  public/themes/admin/default/build/manifest.json
Labels: under review, QA Tested

#42 Security fix: Stored XSS
  packages/Webkul/Admin/src/Http/Controllers/Settings/UserController.php
  packages/Webkul/Admin/src/Http/Controllers/TinyMCEController.php
  packages/Webkul/Admin/src/Http/Controllers/User/AccountController.php
  packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php
  packages/Webkul/Core/src/Filesystem/FileStorer.php
  packages/Webkul/Core/src/Traits/Sanitizer.php
  packages/Webkul/Product/src/Type/AbstractType.php
Labels: QA Tested

#43 fix: import job creation issue due to longtext column in mariadb server
  packages/Webkul/DataTransfer/src/Database/Migrations/2024_10_21_123456_modify_filters_column_to_nullable_in_job_instances_table.php
Labels: under review

#35 Feature/user create command
  composer.json
  packages/Webkul/Installer/src/Console/Commands/DefaultUser.php
  packages/Webkul/Installer/src/Providers/InstallerServiceProvider.php
  packages/Webkul/Installer/tests/Feature/CommandTest.php
  packages/Webkul/Installer/tests/UserCreateCommandTestCase.php
  phpunit.xml
  tests/Pest.php
Labels: under review

#44 fix: old and new values merging issue during import
  packages/Webkul/DataTransfer/src/Helpers/Importers/Category/Importer.php
  packages/Webkul/DataTransfer/src/Helpers/Importers/Product/Importer.php
Labels: under review
